#!/bin/sh
# $Id: start_neutrino,v 1.1 2004/10/07 12:11:27 essu Exp $
sectionsd
timerd
if [ -e /var/bin/camd2 ]; then
 chmod +x /var/bin/camd2
 /var/bin/camd2
else
 /bin/camd2
fi;

if [ -e /var/etc/.pmt_update ] ; then
 zapit -u
else
 zapit
fi;

controld
nhttpd
neutrino -u -f

pzapit -kill

i=9
while expr $i != 0 > /dev/null
do
if pidof controld > /dev/null; then echo "Waiting for controld (max. $i seconds)"
elif pidof timerd > /dev/null; then echo "Waiting for timerd (max. $i seconds)"
elif pidof zapit > /dev/null; then echo "Waiting for zapit (max. $i seconds)"
else break;
fi
i=`expr $i - 1`
sleep 1
done
halt
