#!/bin/sh

# Alles mounten
mount -a

# Pfade setzen
export PATH=/sbin:/bin:/var/plugins

# Pfad zu insmod und den Modules festlegen
export IM="/sbin/insmod"
export MD="/lib/modules/"$(uname -r)"/misc"

# Zeitformat setzen
. /etc/profile

# Den Hostnamen (dbox) festlegen
hostname -F /etc/hostname


# Module laden
  $IM $MD/event.o
  $IM $MD/tuxbox.o
  
  # DVB core
  $IM $MD/dvb-core.o dvb_shutdown_timeout=0

  # I2C core
  $IM $MD/dbox2_i2c.o

  # Frontprozessor
  $IM $MD/dbox2_fp.o
  $IM $MD/dbox2_fp_input.o

  # Misc IO
  $IM $MD/avs.o
  $IM $MD/saa7126.o

# Daten ueber die Box einlesen
  VENDOR=`/bin/tuxinfo -V`
  VENDOR_ID=`/bin/tuxinfo -v`
  MODEL=`/bin/tuxinfo -M`
  MODEL_ID=`/bin/tuxinfo -m`
  SUBMODEL=`/bin/tuxinfo -S`
  SUBMODEL_ID=`/bin/tuxinfo -s`

  # Und ausgeben
  echo "Detected STB:"
  echo "  Vendor: $VENDOR"
  echo "  Model: $MODEL $SUBMODEL"

# Image laeuft nur auf D-BOX2
if [ ! $MODEL_ID -eq 1 ]; then
  halt
fi

# CAM laden
if [ $VENDOR_ID -eq 2 ]; then
  # Philips
  insmod cam mio=0xC040000 firmware=/var/tuxbox/ucodes/cam-alpha.bin
else
  # Andere 
  insmod cam mio=0xC000000 firmware=/var/tuxbox/ucodes/cam-alpha.bin
fi

# Weitere Module
  $IM $MD/dvb_i2c_bridge.o
  $IM $MD/avia_napi.o
  $IM $MD/cam_napi.o
  $IM $MD/dbox2_fp_napi.o

# Falls Netzwerk konfiguriert
if [ -e /etc/network/interfaces ] ; then
  ifup -a &
  test -x /sbin/inetd && inetd
  test -x /sbin/sshd &&/etc/init.d/start_sshd &
fi

# Weitere Module
  $IM $MD/avia_av.o firmware=/var/tuxbox/ucodes

  # Bei Avia_gt hw_sections abfragen
  if [ -e /var/etc/.hw_sections ]; then
    $IM $MD/avia_gt.o ucode=/var/tuxbox/ucodes/ucode.bin hw_sections=0
  else
    $IM $MD/avia_gt.o ucode=/var/tuxbox/ucodes/ucode.bin
  fi;

  $IM $MD/avia_gt_fb.o console_transparent=0
  $IM $MD/lcd.o
  $IM $MD/avia_gt_lirc.o
  $IM $MD/avia_gt_oss.o
  $IM $MD/avia_gt_v4l2.o

  # Je nach Typ weitere Module laden
  if [ $VENDOR_ID -eq 1 ]; then
    #Nokia
    $IM $MD/ves1820.o
    $IM $MD/ves1x93.o board_type=1
  elif [ $VENDOR_ID -eq 2 ]; then
    # Philips
    $IM $MD/tda8044h.o
  elif [ $VENDOR_ID -eq 3 ]; then
    # Sagem
    $IM $MD/at76c651.o
    $IM $MD/ves1x93.o board_type=2
  else
    echo "Hersteller unbekannt"
    halt
  fi

  $IM $MD/avia_av_napi.o

  if [ -e /var/etc/.spts_mode ]; then
    # SPTS-Treiber laden
    $IM $MD/avia_gt_napi.o mode=1
    $IM $MD/dvb2eth.o
  else
    # Keinen SPTS-Treiber laden
    $IM $MD/avia_gt_napi.o
  fi;

  # Lirc konfigurieren, falls Datei existiert
  if [ -e /var/tuxbox/config/lirc/lircd.conf ]; then
    /sbin/lircd /var/tuxbox/config/lirc/lircd.conf
  fi;

  # Telnet-Begruessung schreiben
  echo "$VENDOR $MODEL - Kernel %r (%t)." > /etc/issue.net


# compatibility links
ln -sf demux0 /dev/dvb/adapter0/demux1
ln -sf dvr0 /dev/dvb/adapter0/dvr1
ln -sf fb/0 /dev/fb0

test -x /bin/loadkeys && loadkeys /share/keymaps/i386/qwertz/de-latin1.kmap.gz

if [ -e /etc/init.d/rcS.local ]; then
	. /etc/init.d/rcS.local
fi

# Falls Netzwerk nicht konfiguriert
if [ ! -e /etc/network/interfaces ]; then
  /bin/lcdip
  ifup -a &
  test -x /sbin/inetd && inetd
  test -x /sbin/sshd &&/etc/init.d/start_sshd &
  #Ucodes checken
  /sbin/chkucodes
fi
