#!/bin/sh

. /etc/profile

if test -x /bin/lcdmenu ; then
  lcdmenu
  RC="$?"
  test "$RC" -eq 0 && /var/etc/init.d/start_neutrino
  test "$RC" -eq 1 && /var/etc/init.d/start_enigma
  if test "$RC" -eq 2 ; then
    /bin/lcdip
    ifup -a &
    test -x /sbin/inetd && inetd
    test -x /sbin/sshd &&/etc/init.d/start_sshd &
  fi
elif test -x /bin/neutrino ; then
  if test -x /etc/init.d/start_neutrino ; then
    /etc/init.d/start_neutrino
  elif test -x /var/etc/init.d/start_neutrino ; then
    /var/etc/init.d/start_neutrino
  fi
elif test -x /bin/enigma ; then
  if test -x /etc/init.d/start_enigma ; then
    /etc/init.d/start_enigma
  elif test -x /var/etc/init.d/start_enigma ; then
    /var/etc/init.d/start_enigma
  fi
fi

