#!/bin/sh

. /etc/profile

if test -x /bin/lcdmenu ; then
  lcdmenu
  RC="$?"
  test "$RC" -eq 0 && /etc/init.d/start_neutrino
  test "$RC" -eq 1 && /etc/init.d/start_enigma
elif test -x /bin/neutrino ; then
  /etc/init.d/start_neutrino
elif test -x /bin/enigma ; then
  /etc/init.d/start_enigma
fi

