#!/bin/sh
# $Id: yadi,v 1.16 2004/10/08 23:58:08 essu Exp $
#
# based on allin1.sh,v 1.17 2004/03/26 10:40:22
#
# Copyright (c) 2004 essu, acoo Germany. All rights reserved.
# Mail: acoo@berlios.de
# Mail: essu@berlios.de
#
#
# aktuelle Versionen gibt es hier:
# $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/yadi/Repository/scripts/yadi,v $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA.
#
# Mit diesem Programm koennen Images fuer DBox2 erstellt werden
#
# -------------------------------------------------------
#
#MAIN

VERSION="yadi v. $Revision: 1.16 $"
. check_arguments
. yadi.conf
SCRIPTS=$ROOT/yadi-cvs/scripts
. $SCRIPTS/prepare

if [ ! -e $ROOT/.compileImage ]; then
  # Nur konfigurieren, falls kein Fehler aufgetreten ist
  if [ -e $ROOT/.make_error ];then
    echo; echo "Beim letzten Durchgang ist ein Fehler aufgetreten"
    echo "Make-Vorgang wird an der letzten Position fortgesetzt"; echo
  else
    for FILE in prepare get_cvs prepatch configure patch_cvs y_patch.sh flfs cat_image build_gui enigma_changes neutrino_changes common_gui_changes squashfs_kernel squashfs_move_files squashfs_create_image
    do
     [ -e $SCRIPTS/$FILE ] &&  continue
     echo "$SCRIPTS/$FILE nicht gefunden"; exit 1;
    done
    . $SCRIPTS/check
    . $SCRIPTS/get_cvs
    . $SCRIPTS/prepatch
    . $SCRIPTS/configure
    . $SCRIPTS/patch_cvs
    . $SCRIPTS/flfs
  fi
fi

touch $ROOT/.make_error

if [ $SQUASHFS_ONLY = "no" ]; then
    GUI="neutrino"
    . $SCRIPTS/build_gui
    . $SCRIPTS/neutrino_changes
    . $SCRIPTS/common_gui_changes
    . $SCRIPTS/cat_image
    GUI="enigma"
    . $SCRIPTS/build_gui
    . $SCRIPTS/enigma_changes
    . $SCRIPTS/common_gui_changes
    . $SCRIPTS/cat_image
fi

GUI="all"
. $SCRIPTS/squashfs_update
. $SCRIPTS/build_gui
. $SCRIPTS/neutrino_changes
. $SCRIPTS/enigma_changes
. $SCRIPTS/common_gui_changes
. $SCRIPTS/squashfs_kernel
. $SCRIPTS/squashfs_move_files
. $SCRIPTS/squashfs_create_image

rm $ROOT/.make_error 
rm $ROOT/.compileImage 
echo; echo; echo Images erstellt!; echo Diese sollten sich jetzt in $IMAGES befinden.; echo; echo
exit;
