#!/bin/sh
# $Id: yadi,v 1.13 2004/04/19 17:22:05 essu Exp $
#
# based on allin1.sh,v 1.17 2004/03/26 10:40:22
#
# Copyright (c) 2004 essu, acoo Germany. All rights reserved.
# Mail: acoo@berlios.de
# Mail: essu@berlios.de
#
#
# aktuelle Versionen gibt es hier:
# $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/yadi/Repository/scripts/yadi,v $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA.
#
# Mit diesem Programm koennen Images fuer DBox2 erstellt werden
#
# -------------------------------------------------------
#
#MAIN


VERSION="yadi v. $Revision: 1.13 $"
. check_arguments
. yadi.conf
SCRIPTS=$ROOT/yadi-cvs/scripts

if [ ! -e $ROOT/.compileImage ];then

  . $SCRIPTS/prepare

  # Logfile Anfang
  #echo ""
  #echo "Alle weiteren Ausgaben findet Ihr in der $ROOT/$IMG_PRE.log Datei"
  #{

  # Nur konfigurieren, falls kein Fehler aufgetreten ist
  if [ -e $ROOT/.mkheadall_error ];then
    echo
    echo "Beim letzten Durchgang ist ein Fehler aufgetreten"
    echo "Make-Vorgang wird an der letzten Position fortgesetzt"
    echo
  else
    for FILE in prepare get_cvs configure patch_cvs make_it flfs cat_image build_gui enigma_changes neutrino_changes common_gui_changes squashfs_flfs squashfs_kernel squashfs_move_files squashfs_create_image
    do
      if [ -e $SCRIPTS/$FILE ]; then
        continue;
      else
        echo "$SCRIPTS/$FILE nicht gefunden"
        exit 1;
      fi
    done
    . $SCRIPTS/check
    . $SCRIPTS/get_cvs
    . $SCRIPTS/configure
    . $SCRIPTS/patch_cvs
  fi
  . $SCRIPTS/make_it

fi

. $SCRIPTS/flfs
GUI="neutrino"
. $SCRIPTS/build_gui
. $SCRIPTS/neutrino_changes
. $SCRIPTS/common_gui_changes
. $SCRIPTS/cat_image
GUI="enigma"
. $SCRIPTS/build_gui
. $SCRIPTS/enigma_changes
. $SCRIPTS/common_gui_changes
. $SCRIPTS/cat_image
GUI="all"
. $SCRIPTS/squashfs_update
. $SCRIPTS/build_gui
. $SCRIPTS/neutrino_changes
. $SCRIPTS/enigma_changes
. $SCRIPTS/common_gui_changes
. $SCRIPTS/squashfs_flfs
. $SCRIPTS/squashfs_kernel
. $SCRIPTS/squashfs_move_files
. $SCRIPTS/squashfs_create_image

echo
echo
echo Images erstellt!
echo Diese sollten sich jetzt in $IMAGES befinden.
echo
echo

#} > $ROOT/$IMG_PRE.log 2>&1

exit;
