#!/bin/sh
# $Id: yadiyadd,v 1.1 2004/10/07 12:27:10 essu Exp $
#
# based on allin1.sh,v 1.17 2004/03/26 10:40:22
#
# Copyright (c) 2004 essu, acoo Germany. All rights reserved.
# Mail: acoo@berlios.de
# Mail: essu@berlios.de
#
#
# aktuelle Versionen gibt es hier:
# $Source: /home/xubuntu/berlios_backup/github/tmp-cvs/yadi/Repository/scripts/yadiyadd,v $
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA.
#
# Mit diesem Programm koennen Images fuer DBox2 erstellt werden
#
# -------------------------------------------------------
#
#MAIN

VERSION="yadi v. $Revision: 1.1 $"
. check_arguments
. yadi.conf
SCRIPTS=$ROOT/yadi-cvs/scripts
. $SCRIPTS/prepare

if [ ! -e $ROOT/.compileImage ]; then
  # Nur konfigurieren, falls kein Fehler aufgetreten ist
  if [ -e $ROOT/.make_error ];then
    echo; echo "Beim letzten Durchgang ist ein Fehler aufgetreten"
    echo "Make-Vorgang wird an der letzten Position fortgesetzt"; echo
  else
    for FILE in prepare get_cvs prepatch configure patch_cvs y_patch.sh flfs cat_image build_gui enigma_changes neutrino_changes common_gui_changes squashfs_kernel squashfs_move_files squashfs_create_image
    do
     [ -e $SCRIPTS/$FILE ] &&  continue
     echo "$SCRIPTS/$FILE nicht gefunden"; exit 1;
    done
    . $SCRIPTS/check
    . $SCRIPTS/get_cvs
    . $SCRIPTS/yadd_configure
    . $SCRIPTS/yadd_sfs_kernel
    #. $SCRIPTS/patch_cvs
    #. $SCRIPTS/flfs
  fi
fi

touch $ROOT/.make_error

cd $CVS/cdk
make all

rm $ROOT/.make_error 
rm $ROOT/.compileImage 
echo; echo; echo Images erstellt!; echo Diese sollten sich jetzt in $IMAGES befinden.; echo; echo
exit;
